markers:
  0:
    x:     0.7600
    y:     1.8680
    theta: 0
  1:
    x:     2.0010
    y:     1.4690
    theta: 270
  2:
    x:     0.3750
    y:     3.4970
    theta: 90
  3:
    x:     3.4760
    y:     2.4060
    theta: 270
  5:
    x:     1.8520
    y:     3.1070
    theta: 180
