markers:
  0:
    x:     3.4780
    y:     1.3210
    theta: 90
  1:
    x:     0.7600
    y:     0.3900
    theta: 0
  2:
    x:     1.4750
    y:     3.4950
    theta: 180
  3:
    x:     2.3970
    y:     1.4690
    theta: 0
  5:
    x:     1.4560
    y:     1.8670
    theta: 0
