markers:
  0:
    x:     1.3050
    y:     0.3900
    theta: 270
  1:
    x:     1.3310
    y:     2.5640
    theta: 0
  2:
    x:     2.5470
    y:     1.8710
    theta: 90
  3:
    x:     0.7600
    y:     1.4680
    theta: 180
  5:
    x:     3.0920
    y:     3.1060
    theta: 90
