markers:
  0:
    x:     0.9100
    y:     0.7840
    theta: 90
  1:
    x:     1.4630
    y:     2.0170
    theta: 0
  2:
    x:     0.3750
    y:     3.4970
    theta: 90
  3:
    x:     2.9280
    y:     1.3250
    theta: 270
  5:
    x:     2.5470
    y:     2.4110
    theta: 90
