markers:
  0:
    x:     2.4000
    y:     1.3190
    theta: 90
  1:
    x:     2.4000
    y:     0.9250
    theta: 90
  2:
    x:     2.5500
    y:     1.3250
    theta: 270
  3:
    x:     2.0010
    y:     1.4690
    theta: 90
  5:
    x:     2.5470
    y:     1.4750
    theta: 90
