markers:
  0:
    x:     0.3750
    y:     0.7850
    theta: 90
  1:
    x:     0.7600
    y:     0.7850
    theta: 90
  2:
    x:     0.9100
    y:     0.7840
    theta: 90
  3:
    x:     0.9100
    y:     0.9340
    theta: 90
  5:
    x:     0.3750
    y:     0.9350
    theta: 90
