markers:
  0:
    x:     3.0650
    y:     0.3900
    theta: 270
  1:
    x:     3.4650
    y:     0.3900
    theta: 0
  2:
    x:     3.0650
    y:     0.7810
    theta: 180
  3:
    x:     3.4780
    y:     0.9310
    theta: 270
  5:
    x:     2.9150
    y:     0.3900
    theta: 0
