summary:
  n_folds: 6
  total_test_points: 14
  min_pos_error_m: 0.033539
  mean_pos_error_m: 0.191343
  max_pos_error_m: 0.33918
  mean_ang_error_deg: 0.9119
folds:
- fold: 1
  train_pairs:
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  test_pairs:
  - 1
  fitted:
    c_x: 0.021977
    c_y: 0.010948
    dx_d: -0.030877
    dy_d: -0.022869
    dz_d: 0.008191
    scale: 0.0
  condition_number: 18.45
  degenerate: false
  rms_pos_m: 0.235579
  test_pos_errors_m:
  - 0.308042
  - 0.126907
  mean_ang_err_deg: 0.5727
- fold: 2
  train_pairs:
  - 1
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  test_pairs:
  - 2
  fitted:
    c_x: 0.014803
    c_y: 0.003651
    dx_d: -0.040472
    dy_d: -0.014352
    dz_d: 0.1
    scale: 0.0
  condition_number: 18.36
  degenerate: false
  rms_pos_m: 0.202321
  test_pos_errors_m:
  - 0.202321
  mean_ang_err_deg: 0.2653
- fold: 3
  train_pairs:
  - 1
  - 2
  - 4
  - 5
  - 6
  - 7
  - 8
  test_pairs:
  - 3
  fitted:
    c_x: -0.001613
    c_y: 0.004755
    dx_d: -0.022926
    dy_d: -0.01837
    dz_d: 0.1
    scale: 0.0
  condition_number: 16.13
  degenerate: false
  rms_pos_m: 0.09885
  test_pos_errors_m:
  - 0.118992
  - 0.033539
  - 0.118449
  mean_ang_err_deg: 1.529
- fold: 4
  train_pairs:
  - 1
  - 2
  - 3
  - 5
  - 6
  - 7
  - 8
  test_pairs:
  - 4
  fitted:
    c_x: 0.01542
    c_y: 0.018606
    dx_d: -0.053568
    dy_d: 0.015142
    dz_d: 0.1
    scale: 0.0
  condition_number: 17.39
  degenerate: false
  rms_pos_m: 0.149939
  test_pos_errors_m:
  - 0.110312
  - 0.181093
  mean_ang_err_deg: 0.8611
- fold: 5
  train_pairs:
  - 1
  - 2
  - 3
  - 4
  - 6
  - 7
  - 8
  test_pairs:
  - 5
  fitted:
    c_x: -0.070403
    c_y: -0.037462
    dx_d: -0.009704
    dy_d: 0.00478
    dz_d: 0.07093
    scale: 0.0
  condition_number: 22.09
  degenerate: false
  rms_pos_m: 0.230067
  test_pos_errors_m:
  - 0.282036
  - 0.233646
  - 0.192729
  - 0.227068
  - 0.204489
  mean_ang_err_deg: 0.4546
- fold: 8
  train_pairs:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  test_pairs:
  - 8
  fitted:
    c_x: 0.021727
    c_y: 0.023259
    dx_d: -0.041232
    dy_d: 0.022118
    dz_d: 0.1
    scale: 0.0
  condition_number: 18.53
  degenerate: false
  rms_pos_m: 0.33918
  test_pos_errors_m:
  - 0.33918
  mean_ang_err_deg: 2.7739
