"""
secure_bringup.launch.py
────────────────────────────────────────────────────────────────────────────────
Launches the full collab_nav_ground-jetson stack with the ros2_security
middleware active.

Usage:
  ros2 launch <path>/secure_bringup.launch.py
  ros2 launch <path>/secure_bringup.launch.py certs_dir:=/abs/path/to/certs
  ros2 launch <path>/secure_bringup.launch.py security_disabled:=1   # kill switch

The certs_dir MUST contain:
  ca.crt
  <node_name>.key / <node_name>.crt  for every secured node
  (generated by scripts/generate_certs.sh)

Legacy relay processes bridge the two uncontrolled C++ sensor drivers:
  optitrack_relay — signs optitrack/rigid_body and optitrack/marker
  scan_relay      — signs /scan from oradar lidar
"""

import os

from launch import LaunchDescription
from launch.actions import (
    DeclareLaunchArgument,
    ExecuteProcess,
    SetEnvironmentVariable,
)
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


# ── Project-root certs directory ────────────────────────────────────────────
_PROJ_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
_DEFAULT_CERTS = os.path.join(_PROJ_ROOT, 'certs')
_DEFAULT_POLICY = os.path.join(_PROJ_ROOT, 'config', 'security_policy.yaml')


def generate_launch_description():

    # ── Arguments ────────────────────────────────────────────────────────────
    certs_dir_arg = DeclareLaunchArgument(
        'certs_dir',
        default_value=_DEFAULT_CERTS,
        description='Absolute path to the certificates directory',
    )
    policy_arg = DeclareLaunchArgument(
        'policy_path',
        default_value=_DEFAULT_POLICY,
        description='Absolute path to security_policy.yaml',
    )
    security_disabled_arg = DeclareLaunchArgument(
        'security_disabled',
        default_value='0',
        description='Set to 1 to disable security globally (all nodes revert to native ROS2)',
    )

    # ── Kill switch — must be set BEFORE any Python import runs ─────────────
    # Apply uniformly to every child process; do NOT use additional_env on
    # individual Node actions (that risks a mixed SecureEnvelope/native state).
    set_kill_switch = SetEnvironmentVariable(
        name='ROS2_SECURITY_DISABLED',
        value=LaunchConfiguration('security_disabled'),
    )
    set_policy_env = SetEnvironmentVariable(
        name='ROS2_SECURITY_POLICY',
        value=LaunchConfiguration('policy_path'),
    )

    certs = LaunchConfiguration('certs_dir')

    # ── Legacy relays ────────────────────────────────────────────────────────
    # These bridge uncontrolled C++ drivers into the secured graph at sign level.
    # Run as plain processes (not ROS2 Node actions) per the middleware docs.

    optitrack_relay = ExecuteProcess(
        cmd=[
            'ros2', 'run', 'ros2_security', 'legacy_relay',
            '--level', 'sign',
            '--certs-dir', certs,
            '--node-name', 'optitrack_relay',
            '--bridge', 'geometry_msgs/msg/PoseStamped',
                        '/optitrack/rigid_body', '/optitrack/rigid_body',
            '--bridge', 'geometry_msgs/msg/PointStamped',
                        '/optitrack/marker', '/optitrack/marker',
        ],
        output='screen',
        name='optitrack_relay',
    )

    scan_relay = ExecuteProcess(
        cmd=[
            'ros2', 'run', 'ros2_security', 'legacy_relay',
            '--level', 'sign',
            '--certs-dir', certs,
            '--node-name', 'scan_relay',
            '--bridge', 'sensor_msgs/msg/LaserScan',
                        '/scan', '/scan',
        ],
        output='screen',
        name='scan_relay',
    )

    # ── Controlled Python nodes ───────────────────────────────────────────────

    optitrack_pose = Node(
        package='amr_optitrack',
        executable='optitrack_pose_node',
        name='optitrack_pose_node',
        parameters=[{'certs_dir': certs}],
        output='screen',
    )

    aruco_localizer = Node(
        package='aruco_localizer',
        executable='aruco_localizer',
        name='aruco_localizer',
        parameters=[{'certs_dir': certs}],
        output='screen',
    )

    emergency_stop = Node(
        package='emergency_stop',
        executable='emergency_stop',
        name='emergency_stop',
        parameters=[{'certs_dir': certs}],
        output='screen',
    )

    lidar_odom = Node(
        package='lidar_odometry',
        executable='lidar_odometry',
        name='lidar_odometry_node',
        parameters=[{'certs_dir': certs}],
        output='screen',
    )

    world_mapper = Node(
        package='world_mapper',
        executable='occupancy_mapper',
        name='occupancy_mapper',
        parameters=[{'certs_dir': certs}],
        output='screen',
    )

    map_fusion = Node(
        package='fusion',
        executable='map_fusion_node',
        name='map_fusion_node',
        parameters=[{'certs_dir': certs}],
        output='screen',
    )

    astar_planner2 = Node(
        package='trajectory_planner',
        executable='astar_planner2',
        name='astar_planner2',
        parameters=[{'certs_dir': certs}],
        output='screen',
    )

    spline_follower = Node(
        package='trajectory_planner',
        executable='spline_follower',
        name='spline_follower',
        parameters=[{'certs_dir': certs}],
        output='screen',
    )

    frontier_explorer = Node(
        package='frontier_explorer',
        executable='frontier_explorer',
        name='frontier_explorer',
        parameters=[{'certs_dir': certs}],
        output='screen',
    )

    explorer_controller = Node(
        package='frontier_explorer',
        executable='explorer_controller',
        name='explorer_controller',
        parameters=[{'certs_dir': certs}],
        output='screen',
    )

    mission_orchestrator = Node(
        package='mission_orchestrator',
        executable='orchestrator',
        name='mission_orchestrator',
        parameters=[{'certs_dir': certs}],
        output='screen',
    )

    return LaunchDescription([
        # Arguments
        certs_dir_arg,
        policy_arg,
        security_disabled_arg,
        # Environment (must come before nodes)
        set_kill_switch,
        set_policy_env,
        # Legacy relays (bridge C++ drivers)
        optitrack_relay,
        scan_relay,
        # Controlled Python nodes
        optitrack_pose,
        aruco_localizer,
        emergency_stop,
        lidar_odom,
        world_mapper,
        map_fusion,
        astar_planner2,
        spline_follower,
        frontier_explorer,
        explorer_controller,
        mission_orchestrator,
    ])
